version: "3.3"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: movekrdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
